import "@arco-design/web-react/dist/css/arco.css";
import type { Metadata } from "next";
import '../../public/styles/bootstrap.css';
import '../../public/styles/component.css';
import '../../public/styles/globals.css';
import '../../public/styles/style.css';
import '../../public/styles/utility.css';
import Main from "./main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en">
      <body>
        <Main>
          {children}
        </Main>
      </body>
    </html>
  );
}
